### ISSUE TITLE
Sellix icon too big at checkout

### ISSUE THREAD

**Issue by Lughnasad** [Sellix/woocommerce#2]
[Hummingbird](https://wordpress.org/plugins/hummingbird-performance/) plugin add this css for default:

```css
img {
  height: auto;
  max-width: 100%;
}
```

Here is my own fix:

```css
.payment_method_sellix img {
  height: 32px;
}
```

Would be nice if this is added for future release
